### PR TITLE
Lookup user by email on login

### PR DESCRIPTION
**Pull request by tornqvist**
Detect if `username` is an email address on login and lookup user by email. Implemented just as in NodeBB core: https://github.com/NodeBB/NodeBB/commit/da7d6a31374e9ca9b6c8a1cef67ec3703a40ba8a

Also removed some logging of sensitive data.

### CODE REVIEW

**Comment by LudwikJaniuk** [comment]
@tornqvist The easiest way to get api-like behavior seems to be to put stuff in /api (who would have known ;) ). It actually changes NodeBB's error behavior and you would now get nice errors like:
```
{
    "path": "&#x2F;forum&#x2F;api&#x2F;brfauth&#x2F;uid",
    "error": "[[error:invalid-login-credentials]]"
}
```
I wish I was aware of this earlier but oh well. This change would be breaking tho so do we need to add redirects? While we're at it I'd like to move all api endpoints like this, but I need to know how painful it will be for you to update the references. In any case it would be published as a new version.

**Comment by tornqvist** [comment]
That shouldn't be an issue. As long as we deploy these changes at the same time, I say go ahead and do what needs to be done and I'll make the necessary updates on my side.

**Comment by LudwikJaniuk** [comment]
In that case I'll move the others as well and merge immediatelly. I'll also publish as a new version of the plugin.

**Comment by LudwikJaniuk** [comment]
Pusblished now as version 0.9.0.

**Pull request merged**
